name: everyday
description: dyplom

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  syncfusion_flutter_calendar: 19.4.50
  sizer:
  provider: ^5.0.0
  permission_handler: 8.2.5
  android_alarm_manager_plus: 2.0.3
  flutter_simple_calculator: 2.2.0
  input_calculator: 2.0.0
  google_maps_flutter:
  shared_preferences: 2.0.8
  flutter_native_timezone: 2.0.0
  notification_permissions: 0.6.1
  flutter_local_notifications: 9.3.2
  flutter_time_picker_spinner: 2.0.0
  extended_masked_text: 2.3.1

  flutter_compass: 0.7.0
  flutter_countdown_timer: 4.1.0
  stop_watch_timer: 1.4.0

  firebase_messaging:
  flutter_emoji:
  sqflite: 2.0.0+4
  geolocator: 7.7.1
  date_time_picker: 2.1.0
  duration_picker: 1.1.0+1
  path_provider: 2.0.6
  syncfusion_flutter_datepicker: 19.4.50
  flex_color_picker: 2.1.2
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  assets:
    - assets/images/alarm.png
    - assets/images/calendar.png
    - assets/images/map.png
    - assets/images/note.png
    - assets/images/whiteboard.png
    - assets/images/lustopad.jpg
    - assets/images/mapmarker.png
    - assets/images/money-bag.png
    - assets/images/budget.png
    - assets/images/calculator.png
    - assets/images/chronometer.png
    - assets/images/compass.png
    - assets/images/compassarrow.png
    - assets/images/stopwatch.png
  uses-material-design: true
